name: Obsidian Publish
on: [push, workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Publish obsidian
        uses: project-cool/obsidian-publish-action@main
        with:
          websiteId: "a157901a-413a-42c4-873d-c04d256ce2b8"
          log_level: "info"
          # token: ${{ secrets.NETLIFY_TOKEN }}
