name: Obsidian Publish
on: [push, workflow_dispatch]
jobs:
  PublishObsidian:
    runs-on: ubuntu-latest
    steps:
      - name: Publish obsidian
        uses: project-cool/obsidian-publish-action@main
        with:
          websiteId: "505877b7-1343-488f-a69a-1ab9eb67b179"
          log_level: "info"
          token: ${{ secrets.NETLIFY_TOKEN }}

      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Obsidian publish GitHub action failed
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          to: sarthak.narayan.nitt@gmail.com
          from: GitHub Actions
